In [12]:
# 导包
import time
import numpy as np 
import pandas as pd
from sqlalchemy import create_engine
from pyecharts.charts import Bar3D             
from pyecharts.commons.utils import JsCode
import pyecharts.options as opts

import os
os.chdir(r'/Volumes/C/code/vscode/python/RFM')

### 1.数据加载

In [13]:
# 定义列表, 记录: Excel表名
sheet_names = ['2015', '2016', '2017', '2018', '会员等级']
# 从excel文件中读取数据, 获取到: 字典形式 -> {'2015': df对象, '2016': df对象, ...}
# 参1: Excel文件名(路径)
# 参2: Excel文件中的 表名
sheet_dict = pd.read_excel('./data/sales.xlsx', sheet_name = sheet_names)

# 查看字典中每个df对象(即: 每张sheet表)的 基本信息 和 统计信息.
# step1: 遍历, 获取到每个sheet表名
for i in sheet_names:
    print(i)        # i -> 每个sheet表名
    # step2: 打印 每个sheet表的 基本信息 和 统计信息
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())
    print('-'*50)

2015
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30774 entries, 0 to 30773
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    30774 non-null  int64
 1   订单号     30774 non-null  int64
 2   提交日期    30774 non-null  datetime64[ns]
 3   订单金额    30774 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 961.8 KB
None
               会员ID           订单号                           提交日期  \
count  3.077400e+04  3.077400e+04                          30774
mean   2.918779e+10  4.020414e+09  2015-07-01 20:55:49.424839168
min    2.670000e+02  3.000305e+09            2015-01-01 00:00:00
25%    1.944122e+10  3.885510e+09            2015-04-02 00:00:00
50%    3.746545e+10  4.117491e+09            2015-07-02 00:00:00
75%    3.923593e+10  4.234882e+09            2015-10-01 00:00:00
max    3.954613e+10  4.282025e+09            2015-12-31 00:00:00
std    1.385333e+10  2.630510e+08                            NaN

                订单金额
count   30774.000000
mean      960.991161
min         0.500000
25%        59.000000
50%       139.000000
75%       899.000000
max    111750.000000
std      2068.107231
--------------------------------------------------
2016
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41278 entries, 0 to 41277
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    41278 non-null  int64
 1   订单号     41278 non-null  int64
 2   提交日期    41278 non-null  datetime64[ns]
 3   订单金额    41277 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.3 MB
None
               会员ID           订单号                           提交日期  \
count  4.127800e+04  4.127800e+04                          41278
mean   2.908415e+10  4.313583e+09  2016-07-01 16:34:58.008624384
min    8.100000e+01  4.282026e+09            2016-01-01 00:00:00
25%    1.934990e+10  4.309457e+09            2016-04-01 00:00:00
50%    3.730339e+10  4.317545e+09            2016-07-02 00:00:00
75%    3.923182e+10  4.321132e+09            2016-10-01 00:00:00
max    3.954554e+10  4.324911e+09            2016-12-31 00:00:00
std    1.389468e+10  1.094572e+07                            NaN

                订单金额
count   41277.000000
mean      957.106694
min         0.100000
25%        59.000000
50%       147.000000
75%       888.000000
max    174900.000000
std      2478.560036
--------------------------------------------------
2017
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50839 entries, 0 to 50838
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    50839 non-null  int64
 1   订单号     50839 non-null  int64
 2   提交日期    50839 non-null  datetime64[ns]
 3   订单金额    50839 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.6 MB
None
               会员ID           订单号                           提交日期  \
count  5.083900e+04  5.083900e+04                          50839
mean   2.882368e+10  4.332466e+09  2017-07-02 00:53:06.530025984
min    2.780000e+02  4.324911e+09            2017-01-01 00:00:00
25%    1.869274e+10  4.328415e+09            2017-04-01 00:00:00
50%    3.688044e+10  4.331989e+09            2017-07-02 00:00:00
75%    3.923020e+10  4.337515e+09            2017-10-02 00:00:00
max    3.954554e+10  4.338764e+09            2017-12-31 00:00:00
std    1.409416e+10  4.404350e+06                            NaN

                订单金额
count   50839.000000
mean      963.587872
min         0.300000
25%        59.000000
50%       149.000000
75%       898.000000
max    123609.000000
std      2178.727261
--------------------------------------------------
2018
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81349 entries, 0 to 81348
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    81349 non-null  int64
 1   订单号     81349 non-null  int64
 2   提交日期    81349 non-null  datetime64[ns]
 3   订单金额    81348 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 2.5 MB
None
               会员ID           订单号                           提交日期  \
count  8.134900e+04  8.134900e+04                          81349
mean   2.902317e+10  4.348372e+09  2018-07-01 17:23:17.489827584
min    2.780000e+02  4.338764e+09            2018-01-01 00:00:00
25%    1.902755e+10  4.345654e+09            2018-04-01 00:00:00
50%    3.740121e+10  4.349448e+09            2018-07-01 00:00:00
75%    3.923380e+10  4.351639e+09            2018-10-01 00:00:00
max    3.954614e+10  4.354235e+09            2018-12-31 00:00:00
std    1.404116e+10  4.183774e+06                            NaN

                订单金额
count   81348.000000
mean      966.582792
min         0.000000
25%        60.000000
50%       149.000000
75%       899.000000
max    174900.000000
std      2204.969534
--------------------------------------------------
会员等级
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 2.4 MB
None
               会员ID           会员等级
count  1.543850e+05  154385.000000
mean   2.980055e+10       2.259701
std    1.365654e+10       1.346408
min    8.100000e+01       1.000000
25%    2.213894e+10       1.000000
50%    3.833022e+10       2.000000
75%    3.927932e+10       3.000000
max    3.954614e+10       5.000000
--------------------------------------------------

### 2.数据的预处理

In [14]:
# 1. 遍历, 获取到每张表(除了最后1张):
# 需要处理的动作, 1.删除缺失值.  2.过滤出金额 > 1的订单.  3.固定时间节点, 以每年的最后1天作为当年的 分析节点.
for i in sheet_names[:-1]:
    # 删除缺失值.
    sheet_dict[i] = sheet_dict[i].dropna()
    # 过滤出金额 > 1的订单.
    sheet_dict[i] = sheet_dict[i][sheet_dict[i]['订单金额'] > 1]
    # 固定时间节点, 以每年的最后1天作为当年的 分析节点.
    sheet_dict[i]['max_year_date'] = sheet_dict[i]['提交日期'].max()


# 2. 把上述的 四张表(对应的4个df对象), 合并成一个df对象.
# type(list(sheet_dict.values())[:-1])        # list类型: [df对象, df对象, df对象, df对象] -> 前4张表.
df_merge = pd.concat(list(sheet_dict.values())[:-1], ignore_index = True) # 合并并重置索引.
# 3. 为了好区分, 给df对象新增 year列   
df_merge['year'] = df_merge['提交日期'].dt.year # type: ignore
# 4. 给表新增1列, date_interval 表示本订单购买时间 距 统计节点时间的 差值
df_merge['date_interval'] = df_merge['max_year_date'] - df_merge['提交日期']
# 5. 把date_interval列, 转换为int类型
df_merge['date_interval'] = df_merge['date_interval'].dt.days # type: ignore
df_merge

,会员ID,订单号,提交日期,订单金额,max_year_date,year,date_interval
0,15278002468,3000304681,2015-01-01,499.0,2015-12-31,2015,364
1,39236378972,3000305791,2015-01-01,2588.0,2015-12-31,2015,364
2,38722039578,3000641787,2015-01-01,498.0,2015-12-31,2015,364
3,11049640063,3000798913,2015-01-01,1572.0,2015-12-31,2015,364
4,35038752292,3000821546,2015-01-01,10.1,2015-12-31,2015,364
...,...,...,...,...,...,...,...
202822,39229485704,4354225182,2018-12-31,249.0,2018-12-31,2018,0
202823,39229021075,4354225188,2018-12-31,89.0,2018-12-31,2018,0
202824,39288976750,4354230034,2018-12-31,48.5,2018-12-31,2018,0
202825,26772630,4354230163,2018-12-31,3196.0,2018-12-31,2018,0
202826,39455580335,4354235084,2018-12-31,2999.0,2018-12-31,2018,0

### 3.数据的统计分析

In [15]:
# 1. 基于year 和 会员ID分组, 统计: RFM三项的基本数据. 
# 回顾: RFM: recency(最近一次购买时间), frequency(购买次数), monetary(购买金额)
rfm_gb = df_merge.groupby(['year', '会员ID'], as_index = False).agg({
    'date_interval': 'min',
    '订单号': 'count',
    '订单金额': 'sum'   
})
# 2. 修改列名.
rfm_gb.columns = ['year', '会员ID', 'r', 'f', 'm']
rfm_gb

        year         会员ID    r  f       m
0       2015          267  197  2   105.0
1       2015          282  251  1    29.7
2       2015          283  340  1  5398.0
3       2015          343  300  1   118.0
4       2015          525   37  3   213.0
...      ...          ...  ... ..     ...
148586  2018  39538034299  272  1    49.0
148587  2018  39538034662  189  1  3558.0
148588  2018  39538035729  179  1  3699.0
148589  2018  39545237824  275  1    49.0
148590  2018  39546136285  163  1    19.9

[148591 rows x 5 columns]

In [16]:
# 3. 分别查看下 r, f, m这三列值的分布情况.
rfm_gb.iloc[:, 2:].describe().T

      count         mean          std  min   25%    50%     75%       max
r  148591.0   165.524043   101.988472  0.0  79.0  156.0   255.0     365.0
f  148591.0     1.365002     2.626953  1.0   1.0    1.0     1.0     130.0
m  148591.0  1323.741329  3753.906883  1.5  69.0  189.0  1199.0  206251.8

In [17]:
# 4. 划分区间, 分别给出: RFM的评分, 依据: r: 最近一次购买时间 越小分越高, f: 购买次数 越大分越高, m: 购买金额 越大分越高.
# 基于我们手动指定区间范围, 由系统自动划分区间数, 给出每个范围的 评分(三分法, 低中高)
r_bins = [-1, 79, 255, 365]
f_bins = [0, 2, 5, 130]
m_bins = [1, 69, 1199, 206252]

# r值(最近购买间隔时间)越小, 分越高.
rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins = r_bins, labels = [i for i in range(len(r_bins) - 1, 0, -1)])     
# f值(购买次数)越大, 分越高.
rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins = f_bins, labels = [i for i in range(1, len(f_bins))])    
# m值(购买金额)越大, 分越高.
rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins = m_bins, labels = [i for i in range(1, len(m_bins))])    
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label
0       2015          267  197  2   105.0       2       1       2
1       2015          282  251  1    29.7       2       1       1
2       2015          283  340  1  5398.0       1       1       3
3       2015          343  300  1   118.0       1       1       2
4       2015          525   37  3   213.0       3       2       2
...      ...          ...  ... ..     ...     ...     ...     ...
148586  2018  39538034299  272  1    49.0       1       1       1
148587  2018  39538034662  189  1  3558.0       2       1       3
148588  2018  39538035729  179  1  3699.0       2       1       3
148589  2018  39545237824  275  1    49.0       1       1       1
148590  2018  39546136285  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [18]:
# 5. 统计每个会员的 RFM的评分.   采取方案 -> 拼接.
# step1: 转换类型. 把 r_label, f_label, m_label, 从Categories分类类型 转换为 字符串类型.
rfm_gb['r_label'] = rfm_gb['r_label'].astype(str)
rfm_gb['f_label'] = rfm_gb['f_label'].astype(str)
rfm_gb['m_label'] = rfm_gb['m_label'].astype(str)

# step2: 拼接评分.
rfm_gb['rfm_group'] = rfm_gb['r_label'] + rfm_gb['f_label'] + rfm_gb['m_label']
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label rfm_group
0       2015          267  197  2   105.0       2       1       2       212
1       2015          282  251  1    29.7       2       1       1       211
2       2015          283  340  1  5398.0       1       1       3       113
3       2015          343  300  1   118.0       1       1       2       112
4       2015          525   37  3   213.0       3       2       2       322
...      ...          ...  ... ..     ...     ...     ...     ...       ...
148586  2018  39538034299  272  1    49.0       1       1       1       111
148587  2018  39538034662  189  1  3558.0       2       1       3       213
148588  2018  39538035729  179  1  3699.0       2       1       3       213
148589  2018  39545237824  275  1    49.0       1       1       1       111
148590  2018  39546136285  163  1    19.9       2       1       1       211

[148591 rows x 9 columns]

### 4.导出结果

- 导出结果到Excel文件中.

In [19]:
# 1. 导出结果到Excel文件中, 忽略索引.
rfm_gb.to_excel('./data/sale_rfm_group.xlsx', index = False)

- 导出结果到MySQL表中.

In [20]:
# 1. 创建引擎对象.
engine = create_engine('mysql+pymysql://root:Yrc3099154616@localhost:3306/rfm_db?charset=utf8')

# 2. 具体的导出数据到MySQL表中.
# 参1: 存储结果的数据表名
# 参2: 引擎对象
# 参3: 忽略索引.
# 参4: 如果表存在, 则替换数据.
rfm_gb.to_sql('rfm_table', engine, index = False, if_exists = 'replace')

# 3. 查看数据.
pd.read_sql('select * from rfm_table', engine)

        year         会员ID    r  f       m r_label f_label m_label rfm_group
0       2015          267  197  2   105.0       2       1       2       212
1       2015          282  251  1    29.7       2       1       1       211
2       2015          283  340  1  5398.0       1       1       3       113
3       2015          343  300  1   118.0       1       1       2       112
4       2015          525   37  3   213.0       3       2       2       322
...      ...          ...  ... ..     ...     ...     ...     ...       ...
148586  2018  39538034299  272  1    49.0       1       1       1       111
148587  2018  39538034662  189  1  3558.0       2       1       3       213
148588  2018  39538035729  179  1  3699.0       2       1       3       213
148589  2018  39545237824  275  1    49.0       1       1       1       111
148590  2018  39546136285  163  1    19.9       2       1       1       211

[148591 rows x 9 columns]

### 5.数据可视化

In [21]:
# 1. 准备可视化的数据, 即: rfm_group(分组结果评分), year(统计年份), number(评分个数)
display_data = rfm_gb.groupby(['rfm_group', 'year'], as_index = False).agg({'会员ID': 'count'})

# 2. 修改列名.
display_data.columns = ['rfm_group', 'year', 'number']
# 细节: 把number列的类型 -> int类型.
display_data['number'] = display_data['number'].astype(int)

# 3 绘制图形
# 颜色池
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']

range_max = int(display_data['number'].max())
c = (
    Bar3D()#设置了一个3D柱形图对象
    .add(
        "",#图例
        [d.tolist() for d in display_data.values],#数据
        xaxis3d_opts=opts.Axis3DOpts(type_="category", name='分组名称'),#x轴数据类型，名称，rfm_group
        yaxis3d_opts=opts.Axis3DOpts(type_="category", name='年份'),#y轴数据类型，名称，year
        zaxis3d_opts=opts.Axis3DOpts(type_="value", name='会员数量'),#z轴数据类型，名称，number
    )
    .set_global_opts( # 全局设置
        visualmap_opts=opts.VisualMapOpts(max_=range_max, range_color=range_color), #设置颜色，及不同取值对应的颜色
        title_opts=opts.TitleOpts(title="RFM分组结果"),#设置标题
    )
)
c.render() 		      # 数据保存到本地的网页中.
# c.render_notebook() #在notebook中显示

'/Volumes/C/code/vscode/python/RFM/render.html'